version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"     # Porta do broker AMQP
      - "15672:15672"   # Porta da UI de administração
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - devxpert-academy

networks:
  devxpert-academy:
    driver: bridge

volumes:
  rabbitmq-data: