// <auto-generated />
using System;
using DevXpert.Academy.Financeiro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevXpert.Academy.Financeiro.Data.Migrations
{
    [DbContext(typeof(FinanceiroContext))]
    [Migration("20250430123419_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DevXpert.Academy.Financeiro.Domain.Pagamentos.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("DevXpert.Academy.Financeiro.Domain.Pagamentos.Pagamento", b =>
                {
                    b.OwnsOne("DevXpert.Academy.Financeiro.Domain.Pagamentos.ValuesObejcts.DadosCartao", "DadosCartao", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Token")
                                .HasColumnType("TEXT")
                                .HasColumnName("DadosCartaoToken");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamentos");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.OwnsOne("DevXpert.Academy.Financeiro.Domain.Pagamentos.ValuesObejcts.PagamentoSituacao", "Situacao", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DataHoraProcessamento")
                                .HasColumnType("TEXT")
                                .HasColumnName("DataHoraUltimoProcessamento");

                            b1.Property<string>("Mensagem")
                                .HasColumnType("TEXT")
                                .HasColumnName("Mensagem");

                            b1.Property<int>("Situacao")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Situacao");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamentos");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.Navigation("DadosCartao");

                    b.Navigation("Situacao");
                });
#pragma warning restore 612, 618
        }
    }
}
