// <auto-generated />
using System;
using DevXpert.Academy.Conteudo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevXpert.Academy.Conteudo.Data.Migrations
{
    [DbContext(typeof(ConteudoContext))]
    partial class ConteudoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DevXpert.Academy.Conteudo.Domain.Cursos.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("DevXpert.Academy.Conteudo.Domain.Cursos.Curso", b =>
                {
                    b.OwnsMany("DevXpert.Academy.Conteudo.Domain.Cursos.Aula", "Aulas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("CursoId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DataHoraAlteracao")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DataHoraCriacao")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Titulo")
                                .HasColumnType("TEXT");

                            b1.Property<string>("VideoUrl")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("CursoId");

                            b1.ToTable("CursosAulas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CursoId");
                        });

                    b.OwnsOne("DevXpert.Academy.Conteudo.Domain.Cursos.ValuesObjects.ConteudoProgramatico", "ConteudoProgramatico", b1 =>
                        {
                            b1.Property<Guid>("CursoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("CargaHoraria")
                                .HasColumnType("INTEGER")
                                .HasColumnName("CargaHoraria");

                            b1.Property<string>("Descricao")
                                .HasColumnType("TEXT")
                                .HasColumnName("Descricao");

                            b1.HasKey("CursoId");

                            b1.ToTable("Cursos");

                            b1.WithOwner()
                                .HasForeignKey("CursoId");
                        });

                    b.Navigation("Aulas");

                    b.Navigation("ConteudoProgramatico");
                });
#pragma warning restore 612, 618
        }
    }
}
